baseURL = 'https://www.drybrough.nl'
languageCode = 'en-us'
title = 'Hamish Hutchings'
theme = 'personal-web'
enableEmoji = true

[params.intro]
main = "Hamish"
sub = "Cloud Native Engineer, Technical Writer"

[params.main]
latestPublishHeader = "Latest Blog Post"

[taxonomies]
design = "designs"
tech = "techs"

[params]
# breadcrumb = true
accentColor = "white"
mainSections = ["post"]

[params.notFound]
gopher = "/images/profile.jpg"
h1 = "This page doesn't exist (yet)"
p = "Try again later, or if you think it really should then reach out."

[params.sidebar]
  backgroundImage = '/images/background.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = 'rgba(0,0,0,0.6),rgba(0,0,0,0.4)' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/profile.jpg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/moredhel"
  twitter = "https://twitter.com/hamhut1066"
  linkedin = "https://www.linkedin.com/in/hamish-hutchings-77466149/"
  # medium = "https://medium.com/"
  # codepen = "https://codepen.io/"
  # facebook = "https://www.facebook.com/"
  # youtube = "https://www.youtube.com/"
  # instagram = "https://www.instagram.com/"
  # gitlab = "https://gitlab.com/"
  # keybase = "https://keybase.io/"

  [params.contact]
  email = "hamish@drybrough.nl"
  text= "Contact" # text of the contact link in the sidebar. If email params.contact.email is defined

[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/post/"
  weight = -100

[[menu.main]]
  identifier = "contributions"
  name = "OS Contributions"
  title = "Portfolio"
  url = "/contributions/"
  weight = -90

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true